### ISSUE TITLE
Incorrect page scrolling behavior when `initialIndex` or `scrollToIndex` is used

### ISSUE THREAD

**Issue by sparanoid** [oleggrishechkin/react-viewport-list#48] opened 2022-12-12 20:57 UTC
This bug can be reproduced at:

https://codesandbox.io/s/react-viewport-list-forked-pjozx7?file=/src/App.js

It will be scrolled to the bottom of the page automatically when `initialIndex` or `scrollToIndex` is set.

**Comment by oleggrishechkin** [comment] 2022-12-12 21:14
Hi, @sparanoid. Interesting use case. Thank you for reproduction - it really helpful. 

This is predictable behaviour since scrollIntoView is used. Looks like we need to change this logic to regular scrolling with scrollTop/scrollBy or add an option to avoid scrollIntoView. I have a plans to rewrite scrolling via initialIndex or scrollToIndex. I'll keep this case in my mind.

**Comment by oleggrishechkin** [comment] 2022-12-17 15:50
@sparanoid Hi, I published v6.3.0-beta.0. This version contains fix for this issue. Can you check it?

**Comment by oleggrishechkin** [comment] 2022-12-17 15:51
related to https://github.com/oleggrishechkin/react-viewport-list/discussions/43

**Comment by sparanoid** [comment] 2022-12-22 15:24
@oleggrishechkin Thanks for the update! This beta version works as expected for my project.

**Comment by oleggrishechkin** [comment] 2022-12-29 13:42
should be fixed in 6.3.0

**Closed by oleggrishechkin** 2022-12-29 13:42 UTC
