### ISSUE TITLE
List items rendered with undefined

### ISSUE THREAD

**Issue by cph0** [oleggrishechkin/react-viewport-list#56] opened 2023-02-16 08:03 UTC
Using the latest beta version '7.0.0-beta.0', list items are sometimes being rendered with undefined.  This is causing the item renderer code to crash.  

I have created a code sandbox with an example.

[https://codesandbox.io/s/cranky-carson-jwu0wj?file=/src/App.js](url)

**Comment by oleggrishechkin** [comment] 2023-02-16 09:25
> Using the latest beta version '7.0.0-beta.0', list items are sometimes being rendered with undefined.  This is causing the item renderer code to crash.  
> 
> 
> 
> I have created a code sandbox with an example.
> 
> 
> 
> [https://codesandbox.io/s/cranky-carson-jwu0wj?file=/src/App.js](url)

Thank you fir reproduction.

Looks like empty list (when items length = 0) is broken.

**Comment by oleggrishechkin** [comment] 2023-02-16 11:04
@cph0 should be fixed in 7.0.0-beta.1

**Closed** 2023-02-17 08:05 UTC
